app = 'full-stack-open-pokedex-blue-water-344'
primary_region = 'ams'

[build]

[deploy]
  strategy = "canary"
  wait_timeout = "2m"

[[services]]
  internal_port = 5000
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.http_checks]]
  grace_period = "5s"
  interval = "15s"
  method = "get"
  path = "/healthz"
  protocol = "http"
  timeout = "2s"

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
