name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * *'
  push:
    branches:
      - master

jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Deployed URL Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.DEPLOYMENT_URL }}
          status_code: 200
          max_retries: 3
          retry_delay: 10
          timeout: 10
